CREATE TABLE currency(
    symbol VARCHAR(5) NOT NULL,
    name VARCHAR(35) NOT NULL,
    symbol_native VARCHAR(5) NOT NULL,
    decimal_digits INTEGER  NOT NULL,
    rounding INTEGER NOT NULL,
    code VARCHAR(3) NOT NULL PRIMARY KEY,
    name_plural VARCHAR(36) NOT NULL,
);

INSERT INTO currency(code,name,name_plural,symbol,symbol_native,decimal_digits,rounding) VALUES
    ('EUR','Euro','euros','€','€',2,0),
    ('AED','United Arab Emirates Dirham','UAE dirhams','AED','د.إ.‏',2,0),
    ('AFN','Afghan Afghani','Afghan Afghanis','Af','؋',0,0),
    ('XCD','Eastern Caribbean Dollar','Eastern Caribbean Dollars','EC$','$',0,0),
    ('ALL','Albanian Lek','Albanian lekë','ALL','Lek',0,0),
    ('AMD','Armenian Dram','Armenian drams','AMD','դր.',0,0),
    ('AOA','Angolan Kwanza','Angolan Kwanza','Kz','Kz',0,0),
    ('ARS','Argentine Peso','Argentine pesos','AR$','$',2,0),
    ('USD','US Dollar','US dollars','$','$',2,0),
    ('AUD','Australian Dollar','Australian dollars','AU$','$',2,0),
    ('AWG','Aruban Florin','Aruban Florin','Afl.','Afl.',0,0),
    ('AZN','Azerbaijani Manat','Azerbaijani manats','man.','ман.',2,0),
    ('BAM','Bosnia-Herzegovina Convertible Mark','Bosnia-Herzegovina convertible marks','KM','KM',2,0),
    ('BBD','Barbadian dollar','Barbadian dollars','Bds$','$',0,0),
    ('BDT','Bangladeshi Taka','Bangladeshi takas','Tk','৳',2,0),
    ('XOF','CFA Franc BCEAO','CFA francs BCEAO','CFA','CFA',0,0),
    ('BGN','Bulgarian Lev','Bulgarian leva','BGN','лв.',2,0),
    ('BHD','Bahraini Dinar','Bahraini dinars','BD','د.ب.‏',3,0),
    ('BIF','Burundian Franc','Burundian francs','FBu','FBu',0,0),
    ('BMD','Bermudian dollar','Bermudian dollars','BD$','$',0,0),
    ('BND','Brunei Dollar','Brunei dollars','BN$','$',2,0),
    ('BOB','Bolivian Boliviano','Bolivian bolivianos','Bs','Bs',2,0),
    ('BRL','Brazilian Real','Brazilian reals','R$','R$',2,0),
    ('BSD','Bahamian dollar','Bahamian dollars','B$','$',0,0),
    ('BTN','Bhutanese ngultrum','Bhutanese ngultrum','Nu.','Nu.',0,0),
    ('NOK','Norwegian Krone','Norwegian kroner','Nkr','kr',2,0),
    ('BWP','Botswanan Pula','Botswanan pulas','BWP','P',2,0),
    ('BYN','Belarusian Ruble','Belarusian rubles','Br','руб.',2,0),
    ('BZD','Belize Dollar','Belize dollars','BZ$','$',2,0),
    ('CAD','Canadian Dollar','Canadian dollars','CA$','$',2,0),
    ('CDF','Congolese Franc','Congolese francs','CDF','FrCD',2,0),
    ('XAF','CFA Franc BEAC','CFA francs BEAC','FCFA','FCFA',0,0),
    ('CHF','Swiss Franc','Swiss francs','CHF','CHF',2,0),
    ('NZD','New Zealand Dollar','New Zealand dollars','NZ$','$',2,0),
    ('CLP','Chilean Peso','Chilean pesos','CL$','$',0,0),
    ('CNY','Chinese Yuan','Chinese yuan','CN¥','CN¥',2,0),
    ('COP','Colombian Peso','Colombian pesos','CO$','$',0,0),
    ('CRC','Costa Rican Colón','Costa Rican colóns','₡','₡',0,0),
    ('CUP','Cuban peso','Cuban pesoes','$MN','₱',0,0),
    ('CVE','Cape Verdean Escudo','Cape Verdean escudos','CV$','CV$',2,0),
    ('ANG','Netherlands Antillean guilder','Netherlands Antillean guilders','NAƒ','ƒ',0,0),
    ('CZK','Czech Republic Koruna','Czech Republic korunas','Kč','Kč',2,0),
    ('DJF','Djiboutian Franc','Djiboutian francs','Fdj','Fdj',0,0),
    ('DKK','Danish Krone','Danish kroner','Dkr','kr',2,0),
    ('DOP','Dominican Peso','Dominican pesos','RD$','RD$',2,0),
    ('DZD','Algerian Dinar','Algerian dinars','DA','د.ج.‏',2,0),
    ('EGP','Egyptian Pound','Egyptian pounds','EGP','ج.م.‏',2,0),
    ('MAD','Moroccan Dirham','Moroccan dirhams','MAD','د.م.‏',2,0),
    ('ERN','Eritrean Nakfa','Eritrean nakfas','Nfk','Nfk',2,0),
    ('ETB','Ethiopian Birr','Ethiopian birrs','Br','Br',2,0),
    ('FJD','Fijian dollar','Fijian dollars','FJ$','$',0,0),
    ('FKP','Falkland Islands pound','Falkland Islands pound','FK£','£',0,0),
    ('GBP','British Pound Sterling','British pounds sterling','£','£',2,0),
    ('GEL','Georgian Lari','Georgian laris','GEL','GEL',2,0),
    ('GHS','Ghanaian Cedi','Ghanaian cedis','GH₵','GH₵',2,0),
    ('GIP','Gibraltar pound','Gibraltar pounds','£','£',0,0),
    ('GMD','Gambian dalasi','Gambian dalasis','D','D',0,0),
    ('GNF','Guinean Franc','Guinean francs','FG','FG',0,0),
    ('GTQ','Guatemalan Quetzal','Guatemalan quetzals','GTQ','Q',2,0),
    ('GYD','Guyanese dollar','Guyanese dollars','GY$','$',0,0),
    ('HKD','Hong Kong Dollar','Hong Kong dollars','HK$','$',2,0),
    ('HNL','Honduran Lempira','Honduran lempiras','HNL','L',2,0),
    ('HRK','Croatian Kuna','Croatian kunas','kn','kn',2,0),
    ('HTG','Haitian gourde','Haitian gourde','G','G',0,0),
    ('HUF','Hungarian Forint','Hungarian forints','Ft','Ft',0,0),
    ('IDR','Indonesian Rupiah','Indonesian rupiahs','Rp','Rp',0,0),
    ('ILS','Israeli New Sheqel','Israeli new sheqels','₪','₪',2,0),
    ('INR','Indian Rupee','Indian rupees','Rs','₹',2,0),
    ('IQD','Iraqi Dinar','Iraqi dinars','IQD','د.ع.‏',0,0),
    ('IRR','Iranian Rial','Iranian rials','IRR','﷼',0,0),
    ('ISK','Icelandic Króna','Icelandic krónur','Ikr','kr',0,0),
    ('JMD','Jamaican Dollar','Jamaican dollars','J$','$',2,0),
    ('JOD','Jordanian Dinar','Jordanian dinars','JD','د.أ.‏',3,0),
    ('JPY','Japanese Yen','Japanese yen','¥','￥',0,0),
    ('KES','Kenyan Shilling','Kenyan shillings','Ksh','Ksh',2,0),
    ('KGS','Kyrgyzstani som','Kyrgyzstani som','С̲','С̲',0,0),
    ('KHR','Cambodian Riel','Cambodian riels','KHR','៛',2,0),
    ('KMF','Comorian Franc','Comorian francs','CF','FC',0,0),
    ('KPW','North Korean won','North Korean won','₩','₩',0,0),
    ('KRW','South Korean Won','South Korean won','₩','₩',0,0),
    ('KWD','Kuwaiti Dinar','Kuwaiti dinars','KD','د.ك.‏',3,0),
    ('KYD','Cayman Islands dollar','Cayman Islands dollars','CI$','$',0,0),
    ('KZT','Kazakhstani Tenge','Kazakhstani tenges','KZT','тңг.',2,0),
    ('LAK','Lao kip','Lao kip','₭N','₭',0,0),
    ('LBP','Lebanese Pound','Lebanese pounds','LB£','ل.ل.‏',0,0),
    ('LKR','Sri Lankan Rupee','Sri Lankan rupees','SLRs','SL Re',2,0),
    ('LRD','Liberian dollar','Liberian dollars','LD$','$',0,0),
    ('LSL','Lesotho loti','Lesotho maloti','L','L',0,0),
    ('LYD','Libyan Dinar','Libyan dinars','LD','د.ل.‏',3,0),
    ('MDL','Moldovan Leu','Moldovan lei','MDL','MDL',2,0),
    ('MGA','Malagasy Ariary','Malagasy Ariaries','MGA','MGA',0,0),
    ('MKD','Macedonian Denar','Macedonian denari','MKD','MKD',2,0),
    ('MMK','Myanmar Kyat','Myanmar Kyats','MMK','K',0,0),
    ('MNT','Mongolian tögrög','Mongolian tögrög','₮','₮',0,0),
    ('MOP','Macanese Pataca','Macanese patacas','MOP$','MOP$',2,0),
    ('MUR','Mauritian Rupee','Mauritian rupees','MURs','MURs',0,0),
    ('MVR','Maldivian rufiyaa','Maldivian rufiyaa','Rf','ރ',0,0),
    ('MWK','Malawian kwacha','Malawian kwachas','K','K',0,0),
    ('MXN','Mexican Peso','Mexican pesos','MX$','$',2,0),
    ('MYR','Malaysian Ringgit','Malaysian ringgits','RM','RM',2,0),
    ('MZN','Mozambican Metical','Mozambican meticals','MTn','MTn',2,0),
    ('NAD','Namibian Dollar','Namibian dollars','N$','N$',2,0),
    ('XPF','CFP Franc','CFP franc','F','F',0,0),
    ('NGN','Nigerian Naira','Nigerian nairas','₦','₦',2,0),
    ('NIO','Nicaraguan Córdoba','Nicaraguan córdobas','C$','C$',2,0),
    ('NPR','Nepalese Rupee','Nepalese rupees','NPRs','नेरू',2,0),
    ('OMR','Omani Rial','Omani rials','OMR','ر.ع.‏',3,0),
    ('PAB','Panamanian Balboa','Panamanian balboas','B/.','B/.',2,0),
    ('PEN','Peruvian Nuevo Sol','Peruvian nuevos soles','S/.','S/.',2,0),
    ('PGK','Papua New Guinean kina','Papua New Guinean kina','K','K',0,0),
    ('PHP','Philippine Peso','Philippine pesos','₱','₱',2,0),
    ('PKR','Pakistani Rupee','Pakistani rupees','PKRs','₨',0,0),
    ('PLN','Polish Zloty','Polish zlotys','zł','zł',2,0),
    ('PYG','Paraguayan Guarani','Paraguayan guaranis','₲','₲',0,0),
    ('QAR','Qatari Rial','Qatari rials','QR','ر.ق.‏',2,0),
    ('RON','Romanian Leu','Romanian lei','RON','RON',2,0),
    ('RSD','Serbian Dinar','Serbian dinars','din.','дин.',0,0),
    ('RUB','Russian Ruble','Russian rubles','RUB','₽.',2,0),
    ('RWF','Rwandan Franc','Rwandan francs','RWF','FR',0,0),
    ('SAR','Saudi Riyal','Saudi riyals','SR','ر.س.‏',2,0),
    ('SBD','Solomon Islands dollar','Solomon Islands dollars','SI$','$',0,0),
    ('SCR','Seychellois rupee','Seychellois rupee','SRe','SR',0,0),
    ('SDG','Sudanese Pound','Sudanese pounds','SDG','SDG',2,0),
    ('SEK','Swedish Krona','Swedish kronor','Skr','kr',2,0),
    ('SGD','Singapore Dollar','Singapore dollars','S$','$',2,0),
    ('SHP','Saint Helena pound','Saint Helena pound','SH£','£',0,0),
    ('SLL','Sierra Leonean leone','Sierra Leonean leones','Le','Le',0,0),
    ('SOS','Somali Shilling','Somali shillings','Ssh','Ssh',0,0),
    ('SRD','Surinamese dollar','Surinamese dollars','Sr$','$',0,0),
    ('SSP','South Sudanese pound','South Sudanese pounds','SS£','£',0,0),
    ('SYP','Syrian Pound','Syrian pounds','SY£','ل.س.‏',0,0),
    ('SZL','Swazi lilangeni','Swazi emalangeni','L','L',0,0),
    ('THB','Thai Baht','Thai baht','฿','฿',2,0),
    ('TJS','Tajikistani somoni','Tajikistani somoni','SM','SM',0,0),
    ('TMT','Turkmenistan manat','Turkmenistan manat','T','T',0,0),
    ('TND','Tunisian Dinar','Tunisian dinars','DT','د.ت.‏',3,0),
    ('TOP','Tongan Paʻanga','Tongan paʻanga','T$','T$',2,0),
    ('TRY','Turkish Lira','Turkish Lira','TL','TL',2,0),
    ('TTD','Trinidad and Tobago Dollar','Trinidad and Tobago dollars','TT$','$',2,0),
    ('TWD','New Taiwan Dollar','New Taiwan dollars','NT$','NT$',2,0),
    ('TZS','Tanzanian Shilling','Tanzanian shillings','TSh','TSh',0,0),
    ('UAH','Ukrainian Hryvnia','Ukrainian hryvnias','₴','₴',2,0),
    ('UGX','Ugandan Shilling','Ugandan shillings','USh','USh',0,0),
    ('UYU','Uruguayan Peso','Uruguayan pesos','$U','$',2,0),
    ('UZS','Uzbekistan Som','Uzbekistan som','UZS','UZS',0,0),
    ('VEF','Venezuelan Bolívar','Venezuelan bolívars','Bs.F.','Bs.F.',2,0),
    ('VND','Vietnamese Dong','Vietnamese dong','₫','₫',0,0),
    ('VUV','Vanuatu vatu','Vanuatu vatu','VT','VT',0,0),
    ('WST','Samoan tālā','Samoan tālā','WS$','ST',0,0),
    ('YER','Yemeni Rial','Yemeni Rials','YR','ر.ي.‏',0,0),
    ('ZAR','South African Rand','South African Rand','R','R',2,0),
    ('ZMW','Zambian Kwacha','Zambian Kwachas','ZK','ZK',0,0),
    ('ZWL','Zimbabwean Dollar','Zimbabwean Dollars','ZWL$','ZWL$',0,0),
    ('MRU','Mauritanian ouguiya','Mauritanian ouguiya','UM','UM',0,0),
    ('STN','São Tomé and Príncipe dobra','São Tomé and Príncipe dobras','Db','Db',0,0);